### ISSUE TITLE
[Annotation] Allows annotation to carry some additional constant arguments.

### ISSUE THREAD

**Issue by keryell** [triSYCL/sycl#158]
Now https://reviews.llvm.org/D88645 has landed,the TODO should be solved in https://github.com/triSYCL/sycl/blob/sycl/unified/next/clang/lib/Sema/SemaSYCL.cpp#L1992

**Comment by Ralender** [comment]
Fixed in f1686bfe01db0b47c89cdeb3cfd797092d9cf8a2
