### ISSUE TITLE
Are USM allocations supported?

### ISSUE THREAD

**Issue by j-stephan** [triSYCL/sycl#169]
On my workstation USM allocations seem to fail for `hw_emu` mode (a call to `malloc_device` always returns a `nullptr`). Is this currently a supported feature?

**Comment by keryell** [comment]
At some point it should be supported. But currently not with the OpenCL stack we are using.
There is a new plug-in in development using XRT natively which should bring more features like USM and more FPGA features like the Intel pipe extension.

**Comment by j-stephan** [comment]
Thanks for clarifying!
