### ISSUE TITLE
Requires a second invocation of make to build sycl-xocc

### ISSUE THREAD

**Issue by agozillon** [triSYCL/sycl#2]
Currently need to invoke make a second time after the initial compile described in the GetStartedWithSYCLCompiler.md for the sycl-xocc script to be properly "built" into the build/bin directory. Unsure why at the moment, seems to be required for other sycl related things like sycl-check as well.

**Comment by keryell** [comment]
Was it closed by https://github.com/triSYCL/sycl/pull/4 ?
If so, close it.
