### ISSUE TITLE
[SYCL] fpga_pipes.cpp pipe ambiguity error with unistd.h pipe

### ISSUE THREAD

**Issue by agozillon** [triSYCL/sycl#61]
Seems to be something incorrect in the Clang/LLVM/libsycl.so build process or some incorrect system inclusion as part of the SYCL compilation process causing unistd.h to be added (could just be an out of order inclusion). This isn't a problem when using an unmodified Intel SYCL compiler (although technically were behind a few patches so maybe a follow up patch I don't recall fixed it). 

It results in the following:

/storage/ogozillo/intel-sycl/sycl/build/lib/clang/9.0.0/include/CL/sycl/pipes.hpp:18:68: note: candidate found by name lookup is 'cl::sycl::pipe'
template <class name, class dataT, int32_t min_capacity = 0> class pipe {
                                                                   ^
fpga_pipes.cpp:141:11: error: reference to 'pipe' is ambiguous
          pipe<class pipe_type_for_lambdas, int>::read(SuccessCode);
          ^
/usr/include/unistd.h:417:12: note: candidate found by name lookup is 'pipe'
extern int pipe (int __pipedes[2]) __THROW __wur;
           ^

Workaround is just to always be specific that you're using SYCL's pipe i.e. longhand cl::sycl::pipe.

**Comment by agozillon** [comment]
@keryell looked into this a bit via invocation of clang's -E and found that the problem arises from the include of: #include <boost/core/demangle.hpp> (https://github.com/triSYCL/sycl/blob/sycl/unified/master/sycl/include/CL/sycl/xilinx/fpga/kernel_properties.hpp#L19)

As through as series of includes it eventually includes the offending unistd.h file... 

We can fix this by: 
1) Removing the demangle include for now, as I don't believe it's in use anymore, but it's useful to keep on hand in case we do something similar in the future (while it fixes it, not really an ideal solution as I suppose other users will fall prey to the same issue anytime unistd.h is included)
2) just patch and upstream the test to be cl::sycl::pipe rather than the ambiguous pipe
3) Maybe push for a less generic name for the extension if it is causing conflicts with some existing libraries...

**Comment by keryell** [comment]
I guess we can close this when we merge with the upstream version, then.

**Comment by agozillon** [comment]
should be able to yes
