### ISSUE TITLE
[v++] v++ seems to infinite loop

### ISSUE THREAD

**Issue by Ralender** [triSYCL/sycl#79]
This seems to be a bug in hls not triSYCL

v++ from 2020.1 with this command seems to infinte loop.
v++ --target sw_emu --platform xilinx_u200_xdma_201830_2 --xp param:compiler.hlsDataflowStrictMode=off --save-temps -c -k xSYCL17601996295371491662 -o out.xo tmp.xpirbc
tmp.xpirbc is inside this archive [tmp.zip](https://github.com/triSYCL/sycl/files/5223457/tmp.zip)

**Comment by keryell** [comment]
@yu810226 @aisoard can someome run this on some debug version of `v++` to see where it loops as a first start?

**Comment by keryell** [comment]
@Ralender I guess this is solved now?
If so, close the issue.
